"""seed_jobs.py — Curated demo job offers for a fresh database.

These 80 jobs are representative of real data imported from the Azure SQL
Jobs_DW data warehouse (star schema: FACT_JOB_POSTING + dimension tables).
They seed the database on first startup when neither Azure credentials nor the
bundled CSV are available, so the app always has working demo content.

Priority used in main.py on_startup():
  1. Azure SQL Jobs_DW  (if env vars configured)
  2. This seed file     (fast, deterministic — always present in the image)
  3. data_jobs.csv      (40 k rows bundled as heavy fallback)
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy.orm import Session

from .models import Job


# ─── 80 curated representative job offers ────────────────────────────────────
SEED_JOBS: list[dict] = [
    # ── Data Science / ML ────────────────────────────────────────────────────
    {
        "title_short": "Data Scientist",
        "title": "Senior Data Scientist — NLP & LLMs",
        "company_name": "Capgemini France",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 15),
        "salary_rate": "year", "salary_year_avg": 75000.0,
        "skills": "python, pytorch, transformers, nlp, huggingface, sql, git",
        "source": "seed",
    },
    {
        "title_short": "Data Scientist",
        "title": "Data Scientist — Computer Vision",
        "company_name": "Thales Group",
        "location": "Toulouse", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 2, 20),
        "salary_rate": "year", "salary_year_avg": 68000.0,
        "skills": "python, opencv, tensorflow, pytorch, yolo, docker, linux",
        "source": "seed",
    },
    {
        "title_short": "Data Scientist",
        "title": "Machine Learning Scientist — Recommender Systems",
        "company_name": "BlaBlaCar",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 1, 10),
        "salary_rate": "year", "salary_year_avg": 80000.0,
        "skills": "python, scikit-learn, spark, kafka, airflow, aws, sql",
        "source": "seed",
    },
    {
        "title_short": "Data Scientist",
        "title": "Lead Data Scientist — Fraud Detection",
        "company_name": "Société Générale",
        "location": "Paris La Défense", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 4, 5),
        "salary_rate": "year", "salary_year_avg": 92000.0,
        "skills": "python, xgboost, lightgbm, sql, spark, azure, docker",
        "source": "seed",
    },
    {
        "title_short": "Data Scientist",
        "title": "Data Scientist — Time Series Forecasting",
        "company_name": "TotalEnergies",
        "location": "Pau", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 3, 1),
        "salary_rate": "year", "salary_year_avg": 65000.0,
        "skills": "python, prophet, statsmodels, pandas, sql, azure",
        "source": "seed",
    },
    {
        "title_short": "Data Scientist",
        "title": "Applied ML Scientist",
        "company_name": "Criteo",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 2, 8),
        "salary_rate": "year", "salary_year_avg": 88000.0,
        "skills": "python, pytorch, spark, kafka, scala, docker, kubernetes",
        "source": "seed",
    },

    # ── Machine Learning Engineer ─────────────────────────────────────────────
    {
        "title_short": "ML Engineer",
        "title": "Machine Learning Engineer — MLOps",
        "company_name": "OVHcloud",
        "location": "Roubaix", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 20),
        "salary_rate": "year", "salary_year_avg": 72000.0,
        "skills": "python, mlflow, kubeflow, kubernetes, docker, terraform, gcp",
        "source": "seed",
    },
    {
        "title_short": "ML Engineer",
        "title": "MLOps Engineer — Model Deployment",
        "company_name": "Artefact",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 1, 25),
        "salary_rate": "year", "salary_year_avg": 70000.0,
        "skills": "python, mlflow, fastapi, docker, kubernetes, aws, terraform",
        "source": "seed",
    },
    {
        "title_short": "ML Engineer",
        "title": "Machine Learning Platform Engineer",
        "company_name": "Airbus",
        "location": "Toulouse", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 2, 14),
        "salary_rate": "year", "salary_year_avg": 78000.0,
        "skills": "python, pytorch, onnx, docker, kubernetes, azure, ci/cd",
        "source": "seed",
    },
    {
        "title_short": "ML Engineer",
        "title": "Senior ML Engineer — LLM Inference",
        "company_name": "Mistral AI",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 4, 1),
        "salary_rate": "year", "salary_year_avg": 110000.0,
        "skills": "python, pytorch, cuda, triton, transformers, docker, kubernetes",
        "source": "seed",
    },

    # ── Data Engineer ─────────────────────────────────────────────────────────
    {
        "title_short": "Data Engineer",
        "title": "Senior Data Engineer — Cloud & Streaming",
        "company_name": "Decathlon",
        "location": "Villeneuve d'Ascq", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 10),
        "salary_rate": "year", "salary_year_avg": 65000.0,
        "skills": "python, spark, kafka, airflow, dbt, bigquery, gcp, sql",
        "source": "seed",
    },
    {
        "title_short": "Data Engineer",
        "title": "Data Engineer — Lakehouse Architecture",
        "company_name": "SNCF",
        "location": "Saint-Denis", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 2, 5),
        "salary_rate": "year", "salary_year_avg": 60000.0,
        "skills": "python, spark, delta lake, databricks, azure, sql, dbt",
        "source": "seed",
    },
    {
        "title_short": "Data Engineer",
        "title": "Data Pipeline Engineer — Real-Time",
        "company_name": "Leboncoin",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 1, 18),
        "salary_rate": "year", "salary_year_avg": 68000.0,
        "skills": "python, kafka, flink, spark, aws, s3, terraform, docker",
        "source": "seed",
    },
    {
        "title_short": "Data Engineer",
        "title": "Data Engineer — ELT & Orchestration",
        "company_name": "Cdiscount",
        "location": "Bordeaux", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 28),
        "salary_rate": "year", "salary_year_avg": 58000.0,
        "skills": "python, dbt, airflow, snowflake, sql, git, docker",
        "source": "seed",
    },

    # ── Software Engineering ──────────────────────────────────────────────────
    {
        "title_short": "Software Engineer",
        "title": "Backend Engineer — Python/FastAPI",
        "company_name": "Doctolib",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 5),
        "salary_rate": "year", "salary_year_avg": 72000.0,
        "skills": "python, fastapi, postgresql, redis, docker, kubernetes, aws",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Full-Stack Engineer — React & Node",
        "company_name": "Alan",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 2, 22),
        "salary_rate": "year", "salary_year_avg": 68000.0,
        "skills": "typescript, react, node, postgresql, graphql, docker, aws",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Backend Engineer — Java/Spring",
        "company_name": "Amadeus",
        "location": "Sophia Antipolis", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 1, 30),
        "salary_rate": "year", "salary_year_avg": 65000.0,
        "skills": "java, spring, kafka, postgresql, docker, kubernetes, jenkins",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Platform Engineer — Go & Kubernetes",
        "company_name": "Datadog",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 4, 2),
        "salary_rate": "year", "salary_year_avg": 95000.0,
        "skills": "go, kubernetes, docker, prometheus, terraform, aws, linux",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "iOS Developer — Swift/SwiftUI",
        "company_name": "ManoMano",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 2, 16),
        "salary_rate": "year", "salary_year_avg": 62000.0,
        "skills": "swift, swiftui, xcode, git, ci/cd, rest api",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Android Developer — Kotlin",
        "company_name": "Deezer",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Indeed",
        "posted_date": datetime(2024, 3, 12),
        "salary_rate": "year", "salary_year_avg": 62000.0,
        "skills": "kotlin, android, jetpack compose, retrofit, coroutines, git",
        "source": "seed",
    },

    # ── DevOps / SRE / Cloud ──────────────────────────────────────────────────
    {
        "title_short": "DevOps Engineer",
        "title": "DevOps Engineer — AWS & Terraform",
        "company_name": "Veepee",
        "location": "Saint-Denis", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 1, 22),
        "salary_rate": "year", "salary_year_avg": 65000.0,
        "skills": "aws, terraform, kubernetes, docker, ansible, ci/cd, python",
        "source": "seed",
    },
    {
        "title_short": "DevOps Engineer",
        "title": "SRE — Reliability & Observability",
        "company_name": "Contentsquare",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 2, 28),
        "salary_rate": "year", "salary_year_avg": 72000.0,
        "skills": "kubernetes, prometheus, grafana, terraform, go, python, aws",
        "source": "seed",
    },
    {
        "title_short": "DevOps Engineer",
        "title": "Cloud Architect — Azure",
        "company_name": "Atos",
        "location": "Bezons", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 3, 18),
        "salary_rate": "year", "salary_year_avg": 80000.0,
        "skills": "azure, terraform, kubernetes, docker, ansible, python, powershell",
        "source": "seed",
    },
    {
        "title_short": "DevOps Engineer",
        "title": "Infrastructure Engineer — GitLab CI/CD",
        "company_name": "Dalkia",
        "location": "Lyon", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 1, 15),
        "salary_rate": "year", "salary_year_avg": 58000.0,
        "skills": "gitlab, kubernetes, docker, terraform, linux, python, bash",
        "source": "seed",
    },

    # ── Business Intelligence / Analytics ────────────────────────────────────
    {
        "title_short": "Business Analyst",
        "title": "BI Developer — Power BI & DAX",
        "company_name": "Leroy Merlin",
        "location": "Lezennes", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Indeed",
        "posted_date": datetime(2024, 2, 10),
        "salary_rate": "year", "salary_year_avg": 50000.0,
        "skills": "power bi, dax, sql, excel, azure, python",
        "source": "seed",
    },
    {
        "title_short": "Business Analyst",
        "title": "Data Analyst — Tableau & SQL",
        "company_name": "L'Oréal",
        "location": "Clichy", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 7),
        "salary_rate": "year", "salary_year_avg": 52000.0,
        "skills": "tableau, sql, python, excel, gcp, bigquery",
        "source": "seed",
    },
    {
        "title_short": "Business Analyst",
        "title": "Analytics Engineer — dbt & Snowflake",
        "company_name": "Meilleurs Agents",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 1, 8),
        "salary_rate": "year", "salary_year_avg": 58000.0,
        "skills": "dbt, snowflake, sql, python, looker, git",
        "source": "seed",
    },
    {
        "title_short": "Business Analyst",
        "title": "Business Intelligence Lead",
        "company_name": "Accor Hotels",
        "location": "Issy-les-Moulineaux", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 2, 3),
        "salary_rate": "year", "salary_year_avg": 65000.0,
        "skills": "power bi, sql, excel, azure, sap, python",
        "source": "seed",
    },

    # ── Cybersecurity ─────────────────────────────────────────────────────────
    {
        "title_short": "Cybersecurity Analyst",
        "title": "Security Engineer — SOC & SIEM",
        "company_name": "Orange Cyberdefense",
        "location": "Issy-les-Moulineaux", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 25),
        "salary_rate": "year", "salary_year_avg": 62000.0,
        "skills": "splunk, azure sentinel, python, linux, network, wireshark, elastic",
        "source": "seed",
    },
    {
        "title_short": "Cybersecurity Analyst",
        "title": "Penetration Tester",
        "company_name": "Wavestone",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 2, 18),
        "salary_rate": "year", "salary_year_avg": 58000.0,
        "skills": "kali linux, metasploit, python, burp suite, nmap, network",
        "source": "seed",
    },

    # ── Finance / FinTech ─────────────────────────────────────────────────────
    {
        "title_short": "Finance Analyst",
        "title": "Quantitative Analyst — Risk Modelling",
        "company_name": "BNP Paribas",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 1, 20),
        "salary_rate": "year", "salary_year_avg": 90000.0,
        "skills": "python, r, sql, excel, vba, bloomberg, risk management",
        "source": "seed",
    },
    {
        "title_short": "Finance Analyst",
        "title": "Financial Data Analyst",
        "company_name": "AXA",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 3, 3),
        "salary_rate": "year", "salary_year_avg": 60000.0,
        "skills": "excel, sql, power bi, python, vba, sap",
        "source": "seed",
    },

    # ── Product / UX ──────────────────────────────────────────────────────────
    {
        "title_short": "Product Manager",
        "title": "Senior Product Manager — Data Platform",
        "company_name": "Deezer",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 2, 26),
        "salary_rate": "year", "salary_year_avg": 78000.0,
        "skills": "product management, sql, analytics, jira, agile, notion",
        "source": "seed",
    },
    {
        "title_short": "Product Manager",
        "title": "UX Researcher — AI Products",
        "company_name": "Withings",
        "location": "Issy-les-Moulineaux", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 1, 12),
        "salary_rate": "year", "salary_year_avg": 55000.0,
        "skills": "figma, user research, usability testing, analytics, notion",
        "source": "seed",
    },

    # ── Tunisia / Maghreb region ──────────────────────────────────────────────
    {
        "title_short": "Data Scientist",
        "title": "Data Scientist — ML & Analytics",
        "company_name": "Vermeg",
        "location": "Tunis", "country": "Tunisia",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 15),
        "salary_rate": "year", "salary_year_avg": 28000.0,
        "skills": "python, scikit-learn, tensorflow, sql, docker, git",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Java Developer — Spring Boot",
        "company_name": "Sopra Steria Tunisie",
        "location": "Tunis", "country": "Tunisia",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 2, 12),
        "salary_rate": "year", "salary_year_avg": 22000.0,
        "skills": "java, spring, hibernate, postgresql, maven, git, jira",
        "source": "seed",
    },
    {
        "title_short": "Data Engineer",
        "title": "Data Engineer — Azure & dbt",
        "company_name": "Cognizant Tunisie",
        "location": "Tunis", "country": "Tunisia",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 22),
        "salary_rate": "year", "salary_year_avg": 25000.0,
        "skills": "python, dbt, azure, sql, airflow, spark",
        "source": "seed",
    },
    {
        "title_short": "Business Analyst",
        "title": "BI & Reporting Analyst",
        "company_name": "Ooredoo Tunisie",
        "location": "Tunis", "country": "Tunisia",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 1, 28),
        "salary_rate": "year", "salary_year_avg": 20000.0,
        "skills": "power bi, sql, excel, python, sap",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Frontend Developer — Angular & React",
        "company_name": "Telnet",
        "location": "Tunis", "country": "Tunisia",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 2, 7),
        "salary_rate": "year", "salary_year_avg": 18000.0,
        "skills": "typescript, angular, react, html, css, git, node",
        "source": "seed",
    },
    {
        "title_short": "Data Scientist",
        "title": "Data Scientist — NLP Arabic",
        "company_name": "Talan Tunisie",
        "location": "Tunis", "country": "Tunisia",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 3, 8),
        "salary_rate": "year", "salary_year_avg": 26000.0,
        "skills": "python, nlp, transformers, huggingface, arabic, docker",
        "source": "seed",
    },

    # ── Morocco ───────────────────────────────────────────────────────────────
    {
        "title_short": "Data Scientist",
        "title": "Data Scientist — Predictive Maintenance",
        "company_name": "OCP Group",
        "location": "Casablanca", "country": "Morocco",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 2, 15),
        "salary_rate": "year", "salary_year_avg": 30000.0,
        "skills": "python, scikit-learn, time series, sql, spark, azure",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Backend Engineer — Python & FastAPI",
        "company_name": "Sofrecom Maroc",
        "location": "Rabat", "country": "Morocco",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 1, 25),
        "salary_rate": "year", "salary_year_avg": 20000.0,
        "skills": "python, fastapi, postgresql, redis, docker, git",
        "source": "seed",
    },

    # ── Algeria ───────────────────────────────────────────────────────────────
    {
        "title_short": "Software Engineer",
        "title": "Fullstack Developer — React & Django",
        "company_name": "Djezzy Digital",
        "location": "Alger", "country": "Algeria",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 18),
        "salary_rate": "year", "salary_year_avg": 16000.0,
        "skills": "python, django, react, postgresql, docker, git, linux",
        "source": "seed",
    },

    # ── Canada ────────────────────────────────────────────────────────────────
    {
        "title_short": "Data Scientist",
        "title": "Senior Data Scientist — Healthcare AI",
        "company_name": "Coveo",
        "location": "Montréal", "country": "Canada",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 2, 20),
        "salary_rate": "year", "salary_year_avg": 105000.0,
        "skills": "python, pytorch, transformers, sql, aws, docker, kubernetes",
        "source": "seed",
    },
    {
        "title_short": "ML Engineer",
        "title": "Machine Learning Engineer",
        "company_name": "Element AI (ServiceNow)",
        "location": "Montréal", "country": "Canada",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 1, 16),
        "salary_rate": "year", "salary_year_avg": 112000.0,
        "skills": "python, pytorch, mlflow, aws, docker, kubernetes, terraform",
        "source": "seed",
    },

    # ── United Kingdom ────────────────────────────────────────────────────────
    {
        "title_short": "Data Scientist",
        "title": "Principal Data Scientist",
        "company_name": "Babylon Health",
        "location": "London", "country": "United Kingdom",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 4),
        "salary_rate": "year", "salary_year_avg": 115000.0,
        "skills": "python, tensorflow, bayesian, sql, gcp, docker",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Staff Engineer — Distributed Systems",
        "company_name": "Monzo Bank",
        "location": "London", "country": "United Kingdom",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 2, 11),
        "salary_rate": "year", "salary_year_avg": 130000.0,
        "skills": "go, kubernetes, kafka, cassandra, terraform, aws",
        "source": "seed",
    },

    # ── Germany ───────────────────────────────────────────────────────────────
    {
        "title_short": "Data Engineer",
        "title": "Senior Data Engineer — SAP Analytics Cloud",
        "company_name": "SAP SE",
        "location": "Walldorf", "country": "Germany",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 1, 31),
        "salary_rate": "year", "salary_year_avg": 90000.0,
        "skills": "sap, python, sql, azure, kafka, spark, java",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Backend Engineer — Rust & Microservices",
        "company_name": "Zalando",
        "location": "Berlin", "country": "Germany",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 3, 21),
        "salary_rate": "year", "salary_year_avg": 95000.0,
        "skills": "rust, go, kubernetes, kafka, aws, docker, postgresql",
        "source": "seed",
    },

    # ── USA ───────────────────────────────────────────────────────────────────
    {
        "title_short": "Data Scientist",
        "title": "Staff Data Scientist — Growth Analytics",
        "company_name": "Spotify",
        "location": "New York", "country": "United States",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 4, 1),
        "salary_rate": "year", "salary_year_avg": 185000.0,
        "skills": "python, spark, sql, airflow, gcp, tensorflow, r",
        "source": "seed",
    },
    {
        "title_short": "ML Engineer",
        "title": "Senior ML Engineer — Recommendation",
        "company_name": "Netflix",
        "location": "Los Gatos", "country": "United States",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 3, 14),
        "salary_rate": "year", "salary_year_avg": 220000.0,
        "skills": "python, pytorch, spark, scala, aws, kafka, docker",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Senior Software Engineer — Payments",
        "company_name": "Stripe",
        "location": "San Francisco", "country": "United States",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 2, 25),
        "salary_rate": "year", "salary_year_avg": 210000.0,
        "skills": "ruby, go, python, postgresql, kafka, aws, kubernetes",
        "source": "seed",
    },
    {
        "title_short": "Data Engineer",
        "title": "Principal Data Engineer — Open Table Format",
        "company_name": "Databricks",
        "location": "San Francisco", "country": "United States",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 1, 9),
        "salary_rate": "year", "salary_year_avg": 195000.0,
        "skills": "python, spark, scala, delta lake, sql, kubernetes, aws",
        "source": "seed",
    },

    # ── Remote / Anywhere ─────────────────────────────────────────────────────
    {
        "title_short": "Data Scientist",
        "title": "Remote Data Scientist — AI Startup",
        "company_name": "Hugging Face",
        "location": "Anywhere", "country": "Remote",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 30),
        "salary_rate": "year", "salary_year_avg": 130000.0,
        "skills": "python, pytorch, transformers, nlp, docker, git, linux",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Remote Full-Stack Engineer",
        "company_name": "Vercel",
        "location": "Anywhere", "country": "Remote",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 2, 6),
        "salary_rate": "year", "salary_year_avg": 160000.0,
        "skills": "typescript, react, next.js, node, postgresql, aws, vercel",
        "source": "seed",
    },
    {
        "title_short": "DevOps Engineer",
        "title": "Remote DevOps / Platform Engineer",
        "company_name": "GitLab",
        "location": "Anywhere", "country": "Remote",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 1, 14),
        "salary_rate": "year", "salary_year_avg": 140000.0,
        "skills": "go, ruby, kubernetes, terraform, aws, gcp, ci/cd",
        "source": "seed",
    },
    {
        "title_short": "ML Engineer",
        "title": "Remote MLOps Engineer",
        "company_name": "Weights & Biases",
        "location": "Anywhere", "country": "Remote",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 3, 17),
        "salary_rate": "year", "salary_year_avg": 145000.0,
        "skills": "python, pytorch, mlflow, wandb, docker, kubernetes, aws",
        "source": "seed",
    },

    # ── Part-time / Contractor ────────────────────────────────────────────────
    {
        "title_short": "Data Scientist",
        "title": "Freelance Data Scientist — NLP Consulting",
        "company_name": "Malt",
        "location": "Paris", "country": "France",
        "schedule_type": "Contractor", "work_from_home": True,
        "via": "via Malt",
        "posted_date": datetime(2024, 4, 3),
        "salary_rate": "hour", "salary_hour_avg": 500.0,
        "skills": "python, nlp, transformers, fastapi, docker",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Contract Backend Engineer — Django",
        "company_name": "Comet",
        "location": "Paris", "country": "France",
        "schedule_type": "Contractor", "work_from_home": True,
        "via": "via Comet",
        "posted_date": datetime(2024, 2, 9),
        "salary_rate": "hour", "salary_hour_avg": 600.0,
        "skills": "python, django, postgresql, redis, docker, aws",
        "source": "seed",
    },

    # ── Singapore / Asia ──────────────────────────────────────────────────────
    {
        "title_short": "Data Scientist",
        "title": "Data Scientist — FinTech ML",
        "company_name": "Grab",
        "location": "Singapore", "country": "Singapore",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 1, 17),
        "salary_rate": "year", "salary_year_avg": 95000.0,
        "skills": "python, spark, kafka, sql, pytorch, kubernetes, aws",
        "source": "seed",
    },
    {
        "title_short": "ML Engineer",
        "title": "ML Infrastructure Engineer",
        "company_name": "Sea Limited",
        "location": "Singapore", "country": "Singapore",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 2, 23),
        "salary_rate": "year", "salary_year_avg": 100000.0,
        "skills": "python, kubernetes, mlflow, spark, aws, go, terraform",
        "source": "seed",
    },

    # ── Mixed additional roles ────────────────────────────────────────────────
    {
        "title_short": "Data Analyst",
        "title": "Data Analyst — E-commerce Growth",
        "company_name": "Cdiscount",
        "location": "Bordeaux", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Indeed",
        "posted_date": datetime(2024, 3, 6),
        "salary_rate": "year", "salary_year_avg": 45000.0,
        "skills": "sql, python, excel, tableau, google analytics, git",
        "source": "seed",
    },
    {
        "title_short": "Data Analyst",
        "title": "Marketing Data Analyst",
        "company_name": "Publicis Groupe",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 2, 14),
        "salary_rate": "year", "salary_year_avg": 48000.0,
        "skills": "sql, python, google analytics, tableau, excel, r",
        "source": "seed",
    },
    {
        "title_short": "Cloud Engineer",
        "title": "Cloud Engineer — GCP & BigQuery",
        "company_name": "Renault Group",
        "location": "Boulogne-Billancourt", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 1, 24),
        "salary_rate": "year", "salary_year_avg": 68000.0,
        "skills": "gcp, bigquery, terraform, python, kubernetes, docker, sql",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Embedded Software Engineer — C/C++",
        "company_name": "Safran",
        "location": "Massy", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 11),
        "salary_rate": "year", "salary_year_avg": 58000.0,
        "skills": "c, c++, linux, cmake, git, jira, rtos",
        "source": "seed",
    },
    {
        "title_short": "Data Engineer",
        "title": "Data Engineer — Healthcare Analytics",
        "company_name": "Ramsay Santé",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via Indeed",
        "posted_date": datetime(2024, 2, 1),
        "salary_rate": "year", "salary_year_avg": 55000.0,
        "skills": "python, sql, postgresql, airflow, docker, azure",
        "source": "seed",
    },
    {
        "title_short": "Software Engineer",
        "title": "Tech Lead — Node.js & GraphQL",
        "company_name": "Qonto",
        "location": "Paris", "country": "France",
        "schedule_type": "Full-time", "work_from_home": True,
        "via": "via Glassdoor",
        "posted_date": datetime(2024, 4, 4),
        "salary_rate": "year", "salary_year_avg": 90000.0,
        "skills": "node, typescript, graphql, postgresql, redis, docker, kubernetes",
        "source": "seed",
    },
    {
        "title_short": "DevOps Engineer",
        "title": "DevSecOps Engineer",
        "company_name": "Thales DIS",
        "location": "Meudon", "country": "France",
        "schedule_type": "Full-time", "work_from_home": False,
        "via": "via LinkedIn",
        "posted_date": datetime(2024, 3, 16),
        "salary_rate": "year", "salary_year_avg": 70000.0,
        "skills": "kubernetes, docker, trivy, sonarqube, terraform, python, linux",
        "source": "seed",
    },
]


def seed_jobs(db: Session) -> int:
    """Insert seed jobs if the jobs table contains no 'seed' source rows.

    Returns the number of rows inserted (0 if already seeded).
    """
    from .models import Job
    from sqlalchemy import select

    already = db.execute(select(Job).where(Job.source == "seed").limit(1)).first()
    if already:
        return 0

    jobs = [Job(**row) for row in SEED_JOBS]
    db.add_all(jobs)
    db.commit()
    return len(jobs)
